sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ruffwise/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ruffwise/docker-react npm run test